name: Python Code Coverage

on: ['push', 'pull_request']

jobs:
    test: ubuntu-latest
    steps: 
        - name: Check out
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'

        - name: Install Dependencies   
          run: |
            pip install --upgrade pip
            pip install pytest coverage

        - name: Run Test
          run: |
            coverage run -m pytest
            coverage xml

        - name: Upload Coverage artifact
          uses: actions/upload-artifact@v4
          with:
            name: coverage
            path: coverage.* 

    coverage: 
        runs-on: ubuntu-latest
        needs: test
        steps: 
            - name: Check out
              uses: actions/checkout@v3

            - name: Download coverage artifact
              uses: actions/download-artifact@v4
              with:
                  name: coverage

            - name: Upload coverage to Codecov
              uses: codecov/codecov-actions@v5
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  file: coverage.*                          
